spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb?useSSL=false
    username: root
    password: maria
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
    show-sql: true
    open-in-view: false

# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000